### Read canadian cities csv file and list the cities where type is towns, county is *'NaN'* and  province is *'Newfoundland and Labrador'*

In [1]:
import pandas as pd
import numpy as np

In [87]:
import pandas as pd
import numpy as np
a = pd.read_csv("ca-cities-sample.csv")
a[
    (a["type"] == "Town")
    & (a["county"].isna())
    & (a["province"] == "Newfoundland and Labrador")
]

,id,name,county,province,province_code,postcode_area,type,map_reference,latitude,longitude,census_division,area_code,time_zone
216,25465,Terra Nova,NaN,Newfoundland and Labrador,NL,A0C,Town,002D09,48.50250,-54.21444,Division No. 7,709,America/St_Johns
237,25486,Terrenceville,NaN,Newfoundland and Labrador,NL,A0E,Town,001M10,47.65996,-54.70693,Division No. 2,709,America/St_Johns
501,25750,Tilt Cove,NaN,Newfoundland and Labrador,NL,A0K,Town,002E13,49.88611,-55.62694,Division No. 8,709,America/St_Johns
602,25851,Torbay,NaN,Newfoundland and Labrador,NL,A1K,Town,001N10,47.65913,-52.75317,Division No. 1,709,America/St_Johns
694,25943,Traytown,NaN,Newfoundland and Labrador,NL,A0G,Town,002C12,48.66106,-53.97834,Division No. 7,709,America/St_Johns
723,25972,Trepassey,NaN,Newfoundland and Labrador,NL,A0A,Town,001K11,46.74676,-53.36362,Division No. 1,709,America/St_Johns
733,25982,Trinity,NaN,Newfoundland and Labrador,NL,A0C,Town,002C06,48.37547,-53.39466,Division No. 7,709,America/St_Johns
736,25985,Trinity Bay North,NaN,Newfoundland and Labrador,NL,A0C,Town,002C11,48.50151,-53.08145,Division No. 7,709,America/St_Johns
745,25994,Triton,NaN,Newfoundland and Labrador,NL,A0J,Town,002E12,49.51833,-55.61987,Division No. 8,709,America/St_Johns
773,26022,Trout River,NaN,Newfoundland and Labrador,NL,A0K,Town,012G08,49.47393,-58.12529,Division No. 9,709,America/St_Johns
900,26149,Twillingate,NaN,Newfoundland and Labrador,NL,A0G,Town,002E10,49.64431,-54.74362,Division No. 8,709,America/St_Johns

In [100]:
# Your code here

### Show the list of the cities with latitude > 55 and longitude < -111 and with unique timezones

In [117]:
# Your code here
import pandas as pd
import numpy as np
a = pd.read_csv("ca-cities-sample.csv")
a[(a["latitude"] >55) & (a["longitude"] < -111)].drop_duplicates(subset=["time_zone"])

,id,name,county,province,province_code,postcode_area,type,map_reference,latitude,longitude,census_division,area_code,time_zone
20,25269,Tagish,NaN,Yukon,YT,Y0B,Locality,105D08,60.31484,-134.27151,Yukon,250,America/Whitehorse
21,25270,Tahltan,Kitimat-Stikine,British Columbia,BC,V0C,Locality,104J02,58.01667,-131.00000,Kitimat-Stikine,250,America/Vancouver
46,25295,Tamarack,Peace River,British Columbia,BC,V0C,Locality,094H11,57.65000,-121.16667,Peace River,250,America/Dawson_Creek
53,25302,Tangent,NaN,Alberta,AB,T0H,Locality,083N13,55.79861,-117.67889,Division No. 19,587,America/Edmonton
546,25795,Toad River,Northern Rockies,British Columbia,BC,V0C,Locality,094K14,58.85000,-125.23333,Northern Rockies,250,America/Fort_Nelson
801,26050,Tsiigehtchic,NaN,Northwest Territories,NT,X0E,Hamlet,106N05,67.44240,-133.74240,Region 1,867,America/Yellowknife

### Depict only most 3 frequent numbers

In [5]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

In [139]:
# Your code here
ser.value_counts().sort_values(ascending=False).iloc[:3]

1    4
2    4
3    3
dtype: int64

### Import every 37th row of housing dataset as a dataframe with population greater or equal to 800, median house value is less than 123456 and median income is less than 4, and not inland. Show the total bedrooms, total rooms, and ocean proximity of the imported data filtered by median_house_value in ascending order.

In [113]:
# Your code here
filter_ = housing_df_37.loc[
    (housing_df_37["population"] >= 800)
    & (housing_df_37["median_house_value"] < 123456)
    & (housing_df_37["median_income"] < 4)
    & (housing_df_37["ocean_proximity"] != "INLAND")
]

filter_.sort_values(by=["median_house_value"], ascending=True)[
    ["median_house_value", "total_rooms", "total_bedrooms", "ocean_proximity"]
]

       median_house_value  total_rooms  total_bedrooms ocean_proximity
15651             55000.0       2302.0           938.0        NEAR BAY
2553              70200.0       1453.0           293.0      NEAR OCEAN
2590              74100.0       1982.0           495.0      NEAR OCEAN
9768              76600.0       1054.0           269.0       <1H OCEAN
14245             86300.0       2002.0           488.0      NEAR OCEAN
5217              87500.0       2667.0           671.0       <1H OCEAN
14763             87500.0       2350.0           667.0      NEAR OCEAN
18870             88700.0       2161.0           440.0        NEAR BAY
296               90600.0       1594.0           367.0        NEAR BAY
5069              91400.0       1701.0           452.0       <1H OCEAN
5180              94600.0       1481.0           329.0       <1H OCEAN
4995              96500.0       2637.0           588.0       <1H OCEAN
7585              97900.0       1802.0           496.0       <1H OCEAN
5143              99100.0       1812.0           500.0       <1H OCEAN
14097            100000.0       2127.0           658.0      NEAR OCEAN
2627             100500.0       2581.0           499.0      NEAR OCEAN
2664             101900.0       2019.0           496.0       <1H OCEAN
259              102000.0       1547.0           415.0        NEAR BAY
10952            102500.0       2782.0          1077.0       <1H OCEAN
4921             102900.0       1218.0           342.0       <1H OCEAN
37               103900.0       1511.0           390.0        NEAR BAY
4847             105800.0       1555.0           324.0       <1H OCEAN
7400             105900.0        946.0           254.0       <1H OCEAN
17390            108300.0       2374.0           562.0       <1H OCEAN
9694             108500.0       2591.0           739.0       <1H OCEAN
8325             108600.0       2407.0           630.0       <1H OCEAN
1850             109400.0       2739.0           480.0      NEAR OCEAN
15059            109800.0       7906.0          2292.0       <1H OCEAN
15429            111300.0       1846.0           419.0       <1H OCEAN
185              112800.0       5963.0          1344.0        NEAR BAY
5032             113900.0       3889.0          1199.0       <1H OCEAN
19166            114100.0       1585.0           412.0       <1H OCEAN
7178             115100.0        616.0           196.0       <1H OCEAN
14208            115800.0       1790.0           356.0      NEAR OCEAN
14060            118300.0       2344.0           546.0      NEAR OCEAN
14282            120300.0       2197.0           623.0      NEAR OCEAN